[package]
name = "glyphon"
description = "Fast, simple 2D text rendering for wgpu"
version = "0.3.0"
edition = "2021"
homepage = "https://github.com/grovesNL/glyphon.git"
repository = "https://github.com/grovesNL/glyphon"
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
wgpu = "0.14.0"
etagere = "0.2.6"
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "a5903bb", features = ["std", "swash"] }

[dev-dependencies]
winit = "0.27.0"
pollster = "0.2.5"
