[package]
name = "glyphon"
description = "Fast, simple 2D text rendering for wgpu"
version = "0.5.0"
edition = "2021"
homepage = "https://github.com/grovesNL/glyphon.git"
repository = "https://github.com/grovesNL/glyphon"
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
wgpu = { version = "0.19", default-features = false }
etagere = "0.2.10"
cosmic-text = "0.10"
lru = "0.12.1"

[dev-dependencies]
winit = { version = "0.29.10", features = ["rwh_05"] }
wgpu = { version = "0.19", default-features = true }
pollster = "0.3.0"
