[package]
name = "glyphon"
description = "Fast, simple 2D text rendering for wgpu"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/grovesNL/glyphon.git"
repository = "https://github.com/grovesNL/glyphon"
license = "MIT OR Apache-2.0 OR Zlib"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "8e62ca0" }
fontdue = "0.7.2"
etagere = "0.2.6"
pollster = "0.2.5"

[dev-dependencies]
winit = "0.26.1"
